language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt


script:
  - python -m pytest tests/flask_tests.py --cov=
after_success:
  - coveralls
